=== cadeon/masterlink-iwm/apps/ejb3/tests/org/mlink/iwm/iwml/iwml.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="workerType">
        <xs:sequence>
            <xs:element name="billingRate" type="xs:float" minOccurs="0"/>
            <xs:element name="email" type="xs:string" minOccurs="0"/>
            <xs:element name="fname" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="lname" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="organization" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="skills" type="skills"  maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="skillType">
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="level" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="iwmlType">
        <xs:sequence>
            <xs:element name="worker" maxOccurs="unbounded" type="workerType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="skills">
        <xs:sequence>
            <xs:element name="skill" type="skillType" nillable="true" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="iwml" type="iwmlType">
    </xs:element>


</xs:schema>

=== cadeon/masterlink-iwm/apps/ejb3/tests/org/mlink/iwm/iwml/iwml.xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<iwml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="iwml.xsd">
    <worker>
        <billingRate>1.6E2</billingRate>
        <!--Optional:-->
        <email>apovodyrev@yahoo.com</email>
        <!--Optional:-->
        <fname>Andrei</fname>
        <!--Optional:-->
        <lname>Povodyrev</lname>
        <!--Optional:-->
        <organization>N0 Executive</organization>
        <!--Optional:-->
        <type>Internal</type>
        <skills>
            <skill level="Expert" type="Research"/>
            <skill level="Expert" type="Data Entry"/>
        </skills>
    </worker>

</iwml>
